### ISSUE TITLE
Improve error resilience of lock handling

### ISSUE THREAD

**Issue by MichaelEischer** [restic/restic#2715]
restic version: `0.9.6-dev git commit 070d43e2`

Restic currently relies on lock files to ensure mutual exclusion between commands like `backup` and `prune` (and many others). Incorrectly removing a lock file can cause everything (especially when that leads to backup and prune running in parallel) from crashing commands, incomplete indexes to a newly created snapshots that misses most of its data.

Commands lock the repository before starting and unlock it once finished. A lock file is refreshed every 5 minutes (fixed in #2390), to prevent it from becoming stale (= older than 30 minutes). This ensures that a lock file is not accidentally deleted by `unlock` (which some users run automatically before backup/prune/etc.). For correctness it is necessary that a command always holds a valid lock.

Covered by existing issues:
- [x] An interrupted backup might still continue for a short time after removing the lock #1434 -> the global context is canceled before removing the lock file, thus this is already works correctly
- [x] Lock-file refresh permanently complains and creates lots of lock files, when deleting the old lock file fails once as "already deleted". #2562 #2452 https://github.com/restic/restic/issues/2473#issuecomment-555643752 https://github.com/restic/restic/issues/2473#issuecomment-558626995
- [ ] Log spam while retrying to load deleted files: #1523 or #2596 (could be handled by not retrying when a file cannot be found)

Proposed additional behavior changes:
- If the lock-file refresh detects that the old lock disappeared unexpectedly (= the restic run did not try to delete the file itself) this should cause a command to abort. This could also be caused by pausing a backup by putting a laptop into standby and then continuing later on could cause the backup run to loose its lock due to a call to `unlock` that happened in the meantime
- `backup` should check that it holds the lock before creating the snapshot
- [ ] The current command should abort if refreshing the lock fails to succeed within 30 minutes

**Comment by MichaelEischer** [comment]
> An interrupted backup might still continue for a short time after removing the lock #1434 -> the global context is canceled before removing the lock file, thus this is already works correctly

This guarantee actually only exists since #3164 has been merged.

**Comment by jjYBdx4IL** [comment]
One could add something like a unique client/machine id to the lock file and use that to identify whether the client is authorized to remove the lock file. The authorization could be given implicitly by acquiring a machine-specific semaphore, which would make sure there is no other restic process accessing the same repo from the same machine.
