### ISSUE TITLE
Refactor and cleanup fs code from internal/restic

### ISSUE THREAD

**Issue by MichaelEischer** [restic/restic#5021]
The `internal/restic` package contains a large amount of code that directly interacts with the filesystem in order to fill in information for `restic.Node` objects. This code should move into the `internal/fs` package.

Besides that the code should be cleaned up in several regards:
- [ ] move code and reduce API interface of fs package
- [ ] limit our custom fs code to backup/restore usage. For other code like the backend or cache, the go standard library should be mostly up to the task.
- [ ] work with file handles instead of paths to properly handle disappearing files https://github.com/restic/restic/issues/3098

**Comment by MichaelEischer** [comment]
> Would this change also allow to detect windows reparse points which cannot be backed up ?

I'm not exactly sure what you mean by that. Starting from Go 1.23.0, reparse points will be treated like normal directories and thus restic will start backing those up. In fact you could just give restic 0.17.1 a try which is built using Go 1.23.1.

**Comment by deajan** [comment]
> I'm not exactly sure what you mean by that. Starting from Go 1.23.0, reparse points will be treated like normal directories and thus restic will start backing those up. In fact you could just give restic 0.17.1 a try which is built using Go 1.23.1.

Wow, now this is really bad news for a lot of Nextcloud / Onedrive / Dropbox / Whatever  users.
I've just made a test on Windows 11 with Nextcloud client and restic 0.17.1.

When using windows reparse points (eg virtual place holders for cloud files), you get to have a file hierarchy on your disk, which actually is stored in cloud, and you only get a local copy once you open a file, which is downloaded on the fly:
![image](https://github.com/user-attachments/assets/dd801008-b42b-4889-ad73-9363a495e879)

Once I did a backup with restic, my cloud client (Nextcloud desktop) started to download all the reparse points data in order to have a local copy of the file:
![image](https://github.com/user-attachments/assets/89148dfb-4806-48aa-b9ef-b496a9913210)

I don't use virtual cloud files myself (I hate them), but alot of customers do in order to have the full file hierarchy of their company on disk without needing the actual disk space.

Now once restic will run, it will just ask the virtual cloud files provider to download everything, taking huge bandwidth and storage space, we're talking about hundreds of GB for some setups I am aware of.

While I do understand that I could add excludes on every restic windows setup I know, it's a huge pain, and there will be unforseen consequences for people who don't know about the issue and run restic.

I've asked this once before here, is there a way to have a (optin) option to exclude reparse points from backups (like `--no-windows-reparse-points`) ?

Thanks for any insight.

**Comment by MichaelEischer** [comment]
> I've asked this once before here, is there a way to have a (optin) option to exclude reparse points from backups (like `--no-windows-reparse-points`) ?

There is https://github.com/restic/restic/pull/4990 although it's not finished yet.

> > I'm not exactly sure what you mean by that. Starting from Go 1.23.0, reparse points will be treated like normal directories and thus restic will start backing those up. In fact you could just give restic 0.17.1 a try which is built using Go 1.23.1.
> 
> Wow, now this is really bad news for a lot of Nextcloud / Onedrive / Dropbox / Whatever users. I've just made a test on Windows 11 with Nextcloud client and restic 0.17.1.

I'm pretty sure that this particular behavior hasn't changed at all. Otherwise, the just mentioned PR wouldn't exist.

But I've omitted too many details: I was thinking about reparse points in terms of junctions that are used to mount a filesystem at some folder or to implement symlinks. Those should be reported as directories or symlinks. But you're right cloud files are also reparse points. However, I would have expected the go 1.23 changes to change their filetype to "Irregular" in which case restic should skip backing up the file.

So, something else might also be going on here. But someone will have debug that and suggest a proper fix. With that I'd like to move that discussion back to https://github.com/restic/restic/issues/3697 or https://github.com/restic/restic/issues/3674 .

**Comment by deajan** [comment]
@MichaelEischer Indeed, I did not have enough sleep when I first made that comment.
I've checked behavior between restic 0.16.4 and 0.17.1, except of the error message that repeats the filename it can't read twice, there are no bahavior changes. Sorry for the noise.
